name: smart_hospital
description: Smart Hospital - AI-driven Chest X-ray & Management
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  http: ^1.2.2
  file_picker: ^8.3.7
  url_launcher: ^6.3.2
  intl: ^0.19.0
  logger: ^2.5.0
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  meta: ^1.15.0
  provider: ^6.1.5+1
  
  # Material 3
  flutter_material_color_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
